### ISSUE TITLE
Code submit problem

### ISSUE THREAD

**Issue by kk94wang** [st2yang/5525MachineLearning#1]
I asked TA and he made it clear that we should submit code with the exact name in description that can take in arguments like filename, num_split blabla
Just a kind reminder.

**Comment by st2yang** [comment]
@kk94wang Thanks for letting me know. I made some minor modifications.

BTW, do you know why they have num_crossva as the parameter for LDA1dProjection? Since we are doing projection not classification, why we need to do cross validation?

**Comment by kk94wang** [comment]
不知道啊=。=…但是分10个fold最后如果结果取w的平均话，和直接用全部点求m1,m2的结果好像可能没区别？？不对，好像还是有点区别的

**Comment by st2yang** [comment]
我觉得是老师忘记改了，应该不需要cross validation

**Comment by kk94wang** [comment]
You have to submit code that can take in those arguments.  Your code should be able to load the data which is stored as a file.助教都原话，大概要加个读文件的function

**Comment by st2yang** [comment]
要加个微信吗 y1003655384
